version: "3.9"
services:
  zookeeper:
    container_name: "zookeeper"
    image: "wurstmeister/zookeeper:3.4.6"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8088:8080

  kafka1:
    container_name: "kafka1"
    image: "wurstmeister/kafka:2.13-2.7.0"
    ports:
      - 9091:9091
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
      - ZOOKEEPER=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka1

  kafka2:
    container_name: "kafka2"
    image: "wurstmeister/kafka:2.13-2.7.0"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
      - ZOOKEEPER=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka2

  kafka3:
    container_name: "kafka3"
    image: "wurstmeister/kafka:2.13-2.7.0"
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
      - ZOOKEEPER=zookeeper:2181